on: 
  push:
    branches:
      - master

name: Docker Workflow

jobs:
  build_publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # - name: Build Docker Image (Push)
      #   uses: roleypoly/actions-buildkit@master
      #   with:
      #     tag: katie/medkit-bot:latest
      #     platforms: linux/amd64,linux/arm64,linux/arm/v7
      #     rootless: 'false'
      #   env:
      #     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      - name: Login
        run: echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      - name: 
        run: docker run --rm -v $PWD:/tmp/work -v $HOME/.docker:/home/user/.docker --privileged katie/buildkit-qemu-test build --frontend dockerfile.v0 --local context=/tmp/work --local dockerfile=/tmp/work --export-cache type=local,dest=/tmp/cache,mode=max --output type=image,name=katie/medkit-bot:testing,push=true --opt platform=linux/amd64,linux/arm64,linux/arm/v6

      