on: [push]

name: Docker Workflow

jobs:
  build_publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    container:
      image: jonoh/docker-buildx-qemu
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - uses: actions/checkout@v1

      - name: Docker Login
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Buildx Setup
        run: |
          docker buildx create --driver docker-container --use
          docker buildx inspect --bootstrap
          update-binfmts --enable

      - name: Buildx Build
        run: |
          docker buildx build --platform linux/arm64,linux/arm/v7,linux/arm64 --pull -t katie/medkit-bot --push .

      