on: [push]

name: Docker Workflow

jobs:
  build_publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Docker Login
        uses: azure/container-actions/docker-login@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Container
        run: 
          docker run --rm -v $HOME/.docker:/root/docker -v$(pwd):/src jonoh/docker-buildx-qemu "docker buildx build /src -t katie/medkit-bot:${{ github.sha }} --platform linux/amd64,linux/arm64,linux/arm/v7 --push"

      - name: Docker Logout
        uses: azure/container-actions/docker-logout@master
        