on: 
  push:
    branches:
      - master

name: Docker Workflow

jobs:
  build_publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build Docker Image (Push)
        uses: roleypoly/actions-buildkit@master
        with:
          tag: katie/medkit-bot:latest
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          rootless: false
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      